# ===============================
# Application Name
# ===============================
spring.application.name=Amitit_Student_Managment

# ===============================
# Database Configuration (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/Amitit
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Email Configuration (SMTP - Gmail Example)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sakshibari2019@gmail.com
spring.mail.password=pteo uqcw dimi jhqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
